---
directories:
    work_dir: /usr/local/www/data/private/Glycine/max/GmaxWm82ISU_01
    from_annot_dir: v2.1/annotation
    from_genome_dir: v2.1/assembly
prefixes:
    from_annot_prefix: GmaxWm82ISU_01_724_v2.1
    from_genome_prefix: GmaxWm82ISU_01_724_v2.0
collection_info:
    genus: Glycine
    species: max
    gensp: glyma
    accession: Wm82_ISU01
    gnm_ver: gnm2
    ann_ver: ann1
    genome_key: JFPQ
    annot_key: FGFB
readme_info:
    provenance: DOE-JGI
    source: "https://phytozome-next.jgi.doe.gov/info/GmaxWm82ISU_01_v2_1"
    taxid: 3847
    bioproject:
    original_file_creation_date: 2022-07
    local_file_creation_date: 2022-11
    dataset_release_date: 2022-10-11
    contributors: "Bob Stupar, Jeremy Schmutz"
    citation: "Haun WJ, Hyten DL, Xu WW, Gerhardt DJ, Albert TJ, Richmond T, Jeddeloh JA, Jia G, Springer NM, Vance CP, Stupar RM. The composition and origins of genomic variation among individuals of the soybean reference cultivar Williams 82. Plant Physiol. 2011 Feb;155(2):645-55. doi: 10.1104/pp.110.166736. Epub 2010 Nov 29. PMID: 21115807; PMCID: PMC3032456."
    public_access_level: public
    license: Open, with usage agreement
    keywords: "soybean, Wm82, Williams 82, Wm82_ISU01, Wm82-ISU-01"
from_to_genome:
  - 
    from: fa.gz
    to: genome_main.fna
    description: "Primary genome assembly"
  - 
    from: hardmasked.fa.gz
    to: genome_hardmasked.fna
    description: "Genome assembly - softmasked"
  - 
    from: softmasked.fa.gz
    to: genome_softmasked.fna
    description: "Genome assembly - hardmasked"
from_to_as_is:
  - 
    from: repeatmasked_assembly_v2.0.gff3.gz
    to: repeatmasked_assembly.gff3
    description: "GFF with repeat-masking coordinates"
  - 
    from: annotation_info.txt.gz
    to: annotation_info.txt
    description: "Table of gene annotations from JGI"
  - 
    from: defline.txt.gz
    to: defline.txt
    description: "Defline for genes from JGI"
  - 
    from: locus_transcript_name_map.txt.gz
    to: locus_transcript_name_map.txt
    description: "Table of gene ID correspondences among Wm82 assemblies"
from_to_cds_mrna:
  - 
    from: cds.fa.gz
    to: cds.fna
    splice: "\.\d+$"
    description: "cds sequences"
  - 
    from: cds_primaryTranscriptOnly.fa.gz
    to: cds_primary.fna
    splice: "\.\d+$"
    description: "cds sequences - primary only"
  - 
    from: transcript.fa.gz
    to: mrna.fna
    splice: "\.\d+$"
    description: "Transcript sequences"
  - 
    from: transcript_primaryTranscriptOnly.fa.gz
    to: mrna_primary.fna
    splice: "\.\d+$"
    description: "Transcript sequences - primary only"
from_to_protein:
  - 
    from: protein_primaryTranscriptOnly.fa.gz
    to: protein_primary.faa
    splice: "\.\d+\.p"
    strip: "\.p"
    description: "Protein sequences - primary only"
  - 
    from: protein.fa.gz
    to: protein.faa
    splice: "\.\d+\.p"
    strip: "\.p"
    description: "Protein sequences"
from_to_gff:
  - 
    from: gene_exons.gff3.gz
    to: gene_models_exons.gff3
    strip: "\.v2\.1"
    description: "Gene models, with exon features"

