#!/bin/sh
## This script uses yamllint and pajv to validate a YAML file against a provided JSON schema
##
## $ ./validate readme.schema.json README.CDCFrontier.gnm1.GkHc.yml
#
## ajv-cli installation: npm install -g ajv-cli ajv-formats
##
echo "# ---------------------------------"
echo "# $2 YAML syntax..."
yamllint -d "{extends: default,  rules: {document-start: disable, empty-lines: disable, trailing-spaces: disable, line-length: {max: 2000}}}" $2
echo "# $2 schema..."
ajv -c ajv-formats --verbose --coerce-types=array --remove-additional=true --changes -s $1 -d $2
